### ISSUE TITLE
prevo fails to build with GLib 2.82

### ISSUE THREAD

**Issue by bobby285271** [bpeel/prevodb#8]
Hi, when building with GLib 2.82, we got:

```
prevo.c: In function 'search_trie':
prevo.c:454:60: error: invalid operands to binary - (have 'const guint8 *' {aka 'const unsigned char *'} and 'const char *')
  454 |           node_ch_len = (g_utf8_next_char (trie_start + 4) -
      |                                                            ^
  455 |                          (const char *) trie_start - 4);
      |                          ~~~~~~~~~~~~~~~~~~~~~~~~~          
      |                          |
      |                          const char *
prevo.c: In function 'show_matches':
prevo.c:547:60: error: invalid operands to binary - (have 'const guint8 *' {aka 'const unsigned char *'} and 'const char *')
  547 |       character_len = (g_utf8_next_char (search_start + 4) -
      |                                                            ^
  548 |                        (const char *) search_start - 4);
      |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~          
      |                        |
      |                        const char *
```

Full log available at https://hydra.nixos.org/build/274423271/nixlog/1

It looks like `g_utf8_next_char` no longer includes a cast to `char*` since https://gitlab.gnome.org/GNOME/glib/-/merge_requests/4016,

**Comment by bpeel** [comment]
Thanks for the detailed bug report. I’ve added the casts which should hopefully fix it. Please let me know if not.
